# Generated by Django 3.2.7 on 2021-12-07 22:04

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=225)),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=225), blank=True, size=None)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_crated_by', to=settings.AUTH_USER_MODEL)),
                ('project_members', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='members')),
            ],
        ),
        migrations.CreateModel(
            name='Milestones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=225)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('deadline', models.DateField(default=None)),
                ('status', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_created_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='project', to='project_manager.project')),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=225)),
                ('details', models.CharField(default='', max_length=1000)),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
                ('tags', models.CharField(blank=True, default='', max_length=225, null=True)),
                ('created_by', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='issue_created_by', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_manager.milestones', verbose_name='milestone')),
                ('project', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_manager.project', verbose_name='project')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=500)),
                ('comment_date', models.DateField(default=django.utils.timezone.now)),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_comment_by', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project_manager.issues', verbose_name='issue')),
            ],
        ),
    ]
