# Generated by Django 3.2.7 on 2021-12-09 20:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_members',
        ),
        migrations.AddField(
            model_name='project',
            name='project_members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
