# Generated by Django 3.2.7 on 2021-12-09 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0002_auto_20211210_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestones',
            name='project',
        ),
    ]
