# Generated by Django 3.2.7 on 2021-12-09 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0003_remove_milestones_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestones',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='project', to='project_manager.project'),
        ),
    ]
